apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dsw-helmchart.fullname" . }}-docworker-claim0
  labels:
    io.kompose.service: docworker-claim0
  {{- include "dsw-helmchart.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.pvc.docworkerClaim0.storageRequest | quote }}