apiVersion: v1
kind: Service
metadata:
  name: {{ include "dsw-helmchart.fullname" . }}-mailer
  labels:
    io.kompose.service: mailer
  {{- include "dsw-helmchart.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: /home/mouhamed/kompose --file ../docker-compose.yml convert --volumes
      hostPath
    kompose.service.nodeport.port: "30002"
    kompose.service.type: nodeport
    kompose.version: 1.32.0 (765fde254)
    kompose.volume.size: 500Mi
spec:
  type: {{ .Values.mailer.type }}
  selector:
    io.kompose.service: mailer
  {{- include "dsw-helmchart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mailer.ports | toYaml | nindent 2 }}